export default function DashboardPage() {
  return (
    <div>
      <h1 className="text-4xl font-bold text-gray-800 mb-8">Dashboard</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-blue-50 p-6 rounded-xl border border-blue-100">
          <h3 className="text-xl font-bold text-blue-800 mb-2">Enrolled Courses</h3>
          <p className="text-3xl font-bold text-blue-600">5</p>
          <p className="text-gray-600 mt-2">Active courses you're currently taking</p>
        </div>
        <div className="bg-green-50 p-6 rounded-xl border border-green-100">
          <h3 className="text-xl font-bold text-green-800 mb-2">Completed Lessons</h3>
          <p className="text-3xl font-bold text-green-600">12</p>
          <p className="text-gray-600 mt-2">Lessons you've finished</p>
        </div>
        <div className="bg-purple-50 p-6 rounded-xl border border-purple-100">
          <h3 className="text-xl font-bold text-purple-800 mb-2">AI Quizzes Taken</h3>
          <p className="text-3xl font-bold text-purple-600">8</p>
          <p className="text-gray-600 mt-2">Quizzes generated by AI</p>
        </div>
      </div>

      <div className="mt-12">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">Recent Activity</h2>
        <div className="bg-white rounded-xl shadow p-6">
          <ul className="space-y-4">
            <li className="flex items-center">
              <div className="w-3 h-3 bg-blue-500 rounded-full mr-4"></div>
              <span>Completed lesson "Introduction to React"</span>
              <span className="ml-auto text-gray-500">2 hours ago</span>
            </li>
            <li className="flex items-center">
              <div className="w-3 h-3 bg-green-500 rounded-full mr-4"></div>
              <span>Generated AI quiz for "Node.js Fundamentals"</span>
              <span className="ml-auto text-gray-500">1 day ago</span>
            </li>
            <li className="flex items-center">
              <div className="w-3 h-3 bg-purple-500 rounded-full mr-4"></div>
              <span>Asked AI doubt: "What is SSR?"</span>
              <span className="ml-auto text-gray-500">3 days ago</span>
            </li>
          </ul>
        </div>
      </div>

      <div className="mt-12">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">Quick Actions</h2>
        <div className="flex flex-wrap gap-4">
          <a
            href="/courses"
            className="bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700 transition"
          >
            Browse Courses
          </a>
          <a
            href="/quiz"
            className="bg-green-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-green-700 transition"
          >
            Generate AI Quiz
          </a>
          <a
            href="/chat"
            className="bg-purple-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-purple-700 transition"
          >
            AI Doubt Chat
          </a>
        </div>
      </div>
    </div>
  );
}